# This is a basic workflow to help you get started with Actions

name: Deploy Ansible VM with Terraform

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Environment variables
    env:
      tf_actions_working_dir: ./terraform # This value need to be project name + -vm (project name is set in ansible-vm-with-arm\ansible-vm.parameters.json)

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
