# This is a basic workflow to help you get started with Actions

name: Deploy Ansible VM with Terraform

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Environment variables
    env:
      tf_actions_working_dir: ./ansible-vm-with-terraform
      
    defaults:
    run:
      working-directory: ${{ env.tf_actions_working_dir }} 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_SP_CREDS }}
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init